_core:
  default_config_hash: WsBAM34ibauG_OwPwUI5zOgYAfEClfcFW28dv3y_T-A
langcode: fr
login_link_enabled: true
login_link_label: 'Utiliser mes identifiants Paris 1'
login_success_message: 'Connexion CAS réussie. '
server:
  version: '3.0'
  protocol: https
  hostname: cas.univ-paris1.fr
  port: 443
  path: /otp
  verify: 0
  cert: ''
gateway:
  enabled: false
  recheck_time: 720
  paths:
    id: request_path
    negate: false
    pages: ''
  method: server_side
forced_login:
  enabled: true
  paths:
    id: request_path
    negate: false
    pages: "/envoyez-carte-voeux\r\n/envoyez-carte-voeux/*\r\n/direct-voeux-2022\r\n/direct-voeux-2022/*\r\n/site/2\r\n/creer-mini-site\r\n/creer-mini-site/*\r\n/mode-emploi-debutant\r\n/mode-emploi-debutant/*\r\n/mode-demploi/*\r\n/accessibilite-web\r\n/accessibilite-web/*\r\n/mode-emploi-avance\r\n/mode-emploi-avance/*\r\n/modifier-ma-page-personnelle/*"
user_accounts:
  prevent_normal_login: false
  auto_register: true
  auto_register_follow_registration_policy: false
  email_assignment_strategy: 1
  email_hostname: ''
  email_attribute: mail
  auto_assigned_roles: {  }
  restrict_password_management: true
  restrict_email_management: true
error_handling:
  login_failure_page: /user/login
  message_validation_failure: 'There was a problem validating your login, please contact a site administrator.'
  message_no_local_account: 'You do not have an account on this website. Please contact a site administrator.'
  message_subscriber_denied_reg: 'You do not have access to log in to this website. Please contact a site administrator if you believe you should have access.'
  message_subscriber_denied_login: 'You do not have access to log in to this website. Please contact a site administrator if you believe you should have access.'
  message_account_blocked: 'Your account is blocked or has not been activated. Please contact a site administrator.'
  message_username_already_exists: 'An account on this website with your username already exists. Please contact a site administrator.'
  message_prevent_normal_login: 'This account must log in using <a href="[cas:login-url]">CAS</a>.'
  message_restrict_password_management: 'The requested account is associated with CAS and its password cannot be managed from this website.'
logout:
  cas_logout: true
  logout_destination: '<front>'
  enable_single_logout: false
  single_logout_session_lifetime: 25
proxy:
  initialize: false
  can_be_proxied: false
  proxy_chains: ''
advanced:
  debug_log: true
  connection_timeout: 10
