adding:
  dependencies:
    config:
      - field.field.paragraph.bp_webform.bp_webform
    module:
      - webform
  content:
    bp_webform:
      type: webform_entity_reference_select
      weight: 2
      region: content
      settings: {  }
      third_party_settings: {  }
removing:
  content:
    translation:
      weight: 10
      settings: {  }
      third_party_settings: {  }
      region: content
