adding:
  dependencies:
    config:
      - filter.format.webform_default
    module:
      - filter
      - system
  permissions:
    - 'access content'
    - 'use text format webform_default'
removing: {  }
