adding:
  dependencies:
    config:
      - field.field.block_content.block_page_404.field_search_form
    module:
      - webform
  content:
    field_search_form:
      type: webform_entity_reference_select
      weight: 30
      region: content
      settings:
        default_data: true
        webforms: {  }
      third_party_settings: {  }
removing: {  }
