piwik_report_server: null
piwik_server_url: 'https://stats.univ-paris1.fr/'
token_auth: null
piwik_reports_token_auth: 21441c7b796b5bdde56458b4fa49e30a
piwik_reports_sites: null
piwik_reports_allowed_sites: '41,42'
