smtp_password: ''
smtp_on: true
smtp_host: localhost
smtp_hostbackup: mailhost.univ-paris1.fr
smtp_port: '25'
smtp_protocol: standard
smtp_username: ''
smtp_from: no-reply@univ-paris1.fr
smtp_fromname: '[d8] Université Paris 1 Panthéon-Sorbonne'
smtp_client_hostname: ''
smtp_client_helo: ''
smtp_allowhtml: '1'
smtp_debugging: false
langcode: fr
smtp_autotls: true
smtp_keepalive: false
smtp_timeout: 30
