adding:
  dependencies:
    config:
      - field.field.paragraph.bp_webform.bp_webform
    module:
      - webform
  content:
    bp_webform:
      type: webform_entity_reference_entity_view
      label: hidden
      settings:
        source_entity: false
      third_party_settings: {  }
      weight: 2
      region: content
removing: {  }
