adding:
  dependencies:
    config:
      - field.field.block_content.block_page_404.field_search_form
    module:
      - webform
  content:
    field_search_form:
      type: webform_entity_reference_entity_view
      label: hidden
      settings:
        source_entity: true
      third_party_settings: {  }
      weight: 3
      region: content
removing: {  }
