adding:
  dependencies:
    module:
      - elasticsearch_connector
      - facets
      - system
      - webform
  permissions:
    - 'access administration pages'
    - 'access any webform configuration'
    - 'access own webform configuration'
    - 'access site reports'
    - 'access webform overview'
    - 'administer elasticsearch cluster'
    - 'administer elasticsearch connector'
    - 'administer elasticsearch index'
    - 'administer facets'
    - 'administer menu'
    - 'administer webform'
    - 'administer webform element access'
    - 'create webform'
    - 'delete any webform submission'
    - 'delete own webform'
    - 'edit any webform'
    - 'edit any webform submission'
    - 'edit own webform'
    - 'edit own webform submission'
    - 'link to any page'
    - 'view any webform submission'
    - 'view own webform submission'
    - 'view the administration theme'
removing: {  }
