adding:
  dependencies:
    module:
      - system
      - webform
  permissions:
    - 'access administration pages'
    - 'access site reports'
    - 'access webform overview'
    - 'administer menu'
    - 'create webform'
    - 'delete any webform submission'
    - 'delete own webform'
    - 'edit own webform'
    - 'edit own webform submission'
    - 'view any webform submission'
    - 'view own webform submission'
    - 'view the administration theme'
removing: {  }
