<?php

/**
 * @file
 * Contains up1_news.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function up1_news_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the up1_news module.
    case 'help.page.up1_news':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Type de contenu News présentant les actualités de l&#039;université.') . '</p>';
      return $output;

    default:
  }
}
