<?php

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_help().
 */
function up1_archive_help($route_name, \Drupal\Core\Routing\RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the up1_global module.
    case 'help.page.up1_archive':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Initiate a snapshot of a specific node on web.archive.org') . '</p>';
      return $output;

    default:
  }
}

/**
 * Gets called after content entity operation has been completed.
 *
 * @param \Drupal\Core\Entity\EntityInterface $entity
 *   An entity object.
 * @param string $op
 *   A string containing the operating that's taking place.
 *
 * @see hook_ENTITY_TYPE_postinsert()
 * @see hook_ENTITY_TYPE_postupdate()
 * @see hook_ENTITY_TYPE_postdelete()
 *
 * @ingroup entity_crud
 */
  function up1_archive_node_postsave(EntityInterface $entity, $op) {
    $id = $entity->id();

    $config = \Drupal::config('up1_archive.settings');
    $nid = $config->get('nid');

    if ((int)$id === (int)$nid) {
      $webservice_url = $config->get('url_web');
      $target_url = $config->get('url_node');
      $access_key =  $config->get('access_key');
      $secret = $config->get('secret_key');

      $http_header = [
        "Content-Type: application/x-www-form-urlencoded",
        "authorization: LOW $access_key:$secret"
      ];

      $data = "url=$target_url&capture_all=on&capture_outlinks=1&capture_screenshot=on&wm-save-mywebarchive=on&email_result=on";

      $curl = curl_init ( $webservice_url );
      curl_setopt($curl, CURLOPT_URL, $webservice_url);
      curl_setopt($curl, CURLOPT_POST, true);
      curl_setopt($curl, CURLOPT_HTTPHEADER, $http_header);
      curl_setopt($curl, CURLOPT_POSTFIELDS, $data);

      curl_exec ( $curl );
      curl_close( $curl );
    }
  }
