label: 'Soumissions de webform'
display:
  default:
    display_options:
      fields:
        view_webform_submission:
          label: Operations
      empty:
        area_text_custom:
          content: 'Aucune soumission n''est disponible.'
      arguments:
        in_draft:
          exception:
            title: All
      title: 'Soumissions de webform'
  embed_default:
    display_options:
      display_description: 'Afficher les soumissions.'
  embed_administer:
    display_options:
      display_description: 'Administrer les soumissions.'
      fields:
        completed:
          label: Terminé
        operations:
          label: Operations
      filters:
        in_draft:
          expose:
            label: 'Est un brouillon'
  embed_manage:
    display_options:
      display_description: 'Gérer les soumissions.'
      fields:
        completed:
          label: Terminé
        view_webform_submission:
          label: Operations
        edit_webform_submission:
          label: Operations
      filters:
        in_draft:
          expose:
            label: 'Est un brouillon'
  embed_review:
    display_options:
      fields:
        completed:
          label: Terminé
        view_webform_submission:
          label: Operations
      filters:
        in_draft:
          expose:
            label: 'Est un brouillon'
