label: Contenu
description: 'Trouver et gérer le contenu.'
display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Filtrer
      pager:
        options:
          tags:
            previous: '‹ Précédent'
            next: 'Suivant ›'
      fields:
        type:
          label: 'Type de contenu'
        status:
          label: État
          settings:
            format_custom_false: 'Non publié'
        changed:
          label: 'Mis à jour'
        operations:
          label: Actions
      filters:
        type:
          expose:
            label: 'Type de contenu'
        status:
          expose:
            label: État
          group_info:
            label: 'Statut de publication'
            group_items:
              2:
                title: 'Non publié'
        langcode:
          expose:
            label: Langue
      title: Contenu
      empty:
        area_text_custom:
          content: 'Aucun contenu disponible.'
  page_1:
    display_options:
      menu:
        title: Contenu
      tab_options:
        title: Contenu
        description: 'Trouver et gérer le contenu'
