display:
  default:
    display_title: Principale
    display_options:
      exposed_form:
        options:
          submit_button: Applica
          reset_button_label: Ripristina
          exposed_sorts_label: 'Ordina per'
          sort_asc_label: Asc
          sort_desc_label: Disc
      pager:
        options:
          tags:
            previous: ‹‹
            next: ››
            first: '« Prima'
            last: 'Ultima »'
          expose:
            items_per_page_label: 'Voci per pagina'
            items_per_page_options_all_label: '- Tutto -'
            offset_label: Scostamento
      fields:
        entity_field:
          label: "Campo dell'entità"
          separator: ', '
        entity_langcode:
          label: "Lingua dell'entità"
          separator: ', '
        url:
          label: URL
          separator: ', '
        last_check:
          label: 'Ultimo controllo'
          separator: ', '
        method:
          label: Metodo
          separator: ', '
        code:
          separator: ', '
        error:
          label: Errore
          separator: ', '
        fail_count:
          separator: ', '
        status:
          separator: ', '
        operations:
          label: Operazioni
      filters:
        url:
          expose:
            label: URL
        code_1:
          group_info:
            label: Risultato
            group_items:
              1:
                title: 'Non riuscito'
        entity_langcode:
          expose:
            label: "Lingua dell'entità"
      footer:
        result:
          content: 'Visualizzazione elementi @start - @end su @total'
  page_1:
    display_title: Pagina
