settings:
  default_form_close_message: 'Sorry…This form is closed to new submissions.'
  default_submit_button_label: Invia
  default_reset_button_label: Ripristina
  default_delete_button_label: Elimina
  default_form_confidential_message: 'Ce formulaire est confidentiel. Vous devez vous <a href="[site:login-url]/logout?destination=[current-page:url:relative]">déconnecter</a> pour l''utiliser.'
  default_wizard_prev_button_label: '< Précédent'
  default_wizard_start_label: Inizio
  default_wizard_confirmation_label: Completo
  default_wizard_toggle_show_label: 'Mostra tutti'
  default_preview_next_button_label: Anteprima
  default_preview_prev_button_label: '< Précédent'
  default_preview_label: Anteprima
  default_preview_title: '[webform:title] : Prévisualisation'
  default_draft_button_label: 'Salva bozza'
  default_draft_saved_message: 'Inserimento salvato. Puoi tornare al form più tardi i valori attualmente inseriti saranno recuperati.'
  default_draft_loaded_message: 'Un formulaire partiellement complété a été trouvé. Veuillez compléter les portions restantes.'
  default_confirmation_message: 'Nouvelle soumission ajoutée à [webform:title]'
  default_confirmation_back_label: 'Retour au formulaire'
  default_submission_locked_message: 'Cette soumission a été verrouillée.'
  dialog_options:
    narrow:
      title: Stretto
    normal:
      title: Normale
    wide:
      title: Largo
element:
  empty_message: '{Vide}'
  default_more_title: Altro
mail:
  default_body_html: "<p>Envoyé le [webform_submission:created]</p>\r\n<p>Envoyé par : [webform_submission:user]</p>\r\n<p>Les valeurs soumises sont :</p>\r\n[webform_submission:values]\n"
