<?php

/**
 * @file
 * Contains up1_global.module.
 */

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Cache\Cache;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Url;
use Drupal\node\NodeInterface;
use Drupal\micro_site\entity\Site;
use Drupal\node\Entity\Node;

/**
 * Implements hook_help().
 */
function up1_global_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the up1_global module.
    case 'help.page.up1_global':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Defines global functions to be reused in other UP1 modules') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_alter().
 */
function up1_global_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == "node_offer_form") {
    $form['field_type']['#autocomplete_route_name'] = 'up1_global.referens';
    $form['field_type']['#autocomplete_route_parameters'] = [
      'bap' => 'bap',
    ];
  }
  if($form_id == "centres_up1_form"){
    $form['submit']['#value'] = html_entity_decode('&#xf002;');
  }
  if ($form['#id'] == "views-exposed-form-recherche-de-contenu-page-1"){
    $form["actions"]['submit']['#value'] = html_entity_decode('&#xf002;');
  }

  if ($form_id == "node_page_edit_form") {
    foreach (array_keys($form['actions']) as $action) {
      if ($action != 'preview' && isset($form['actions'][$action]['#type'])
        && $form['actions'][$action]['#type'] === 'submit') {
        $form['actions'][$action]['#submit'][] = 'up1_global_contact_paragraph_submit';
      }
    }
  }

}

function up1_global_contact_paragraph_submit($form, FormStateInterface $form_state) {}

/**
 * Implements hook_theme().
 */
function up1_global_theme($existing, $type, $theme, $path) {
  return [
    'date_range_formatter' => [
      'variables' => [],
      'template' => 'date-range-formatter',
    ],
    'up1_ent_search_block' => [
      'variables' => ['url' => NULL, 'theme_url' => NULL],
      'template' => 'up1-ent-search-block',
    ],
    'details_centre_up1' => [
      'variables' => [
        'centre' => NULL
      ],
      'template' => 'details-centre-up1'
    ],
    'up1_site_switcher_block' => [
      'variables' => [
        'current_language' => NULL,
        'french_version' => NULL,
        'english_version' => NULL,
      ],
      'template' => 'up1-site-switcher-block',
    ],
  ];
}

/**
 * Implements hook_language_switch_links_alter().
 */
function up1_global_language_switch_links_alter(array &$links, $type, Url $url) {
  if ($node = \Drupal::routeMatch()->getParameter('node')) {
    foreach ($links as $langcode => $link) {
      if ($node && !array_key_exists($langcode, $node->getTranslationLanguages(TRUE))) {
        //There is no translation in that language, unset the whole thing
        unset($links[$langcode]);
      }
    }
  }
}

/**
 * Implements hook_cron().
 */
function up1_global_cron() {
  invalidate_homepage_agenda_cron();
  up1_global_hotfix_author_pages_sorbonnetv();
}

/**
 * Implements hook_node_access().
 */
function up1_global_node_access(NodeInterface $node, $op, AccountInterface $account) {
  $langcode = \Drupal::languageManager()->getCurrentLanguage()->getId();
  if (!$node->hasTranslation($langcode)) {
    $access = AccessResult::forbidden();
  }
  else {
    $access = AccessResult::neutral();
  }
  $access->addCacheableDependency($node);
  return $access;
}

function invalidate_homepage_agenda_cron() {
    $request_time = \Drupal::time()->getCurrentTime();
    $state_service = \Drupal::state();
    // Invalidate homepage agenda Cache every day.
    $next_daily_cron = $state_service->get('up1_global.cache_cron_daily', 0);
    if ($next_daily_cron < $request_time) {
        $tomorrow = strtotime('tomorrow 0:59:00');
        $state_service->set('up1_global.cache_cron_daily', $tomorrow);
        Cache::invalidateTags(['time:daily']);
    }
}

/**
 * Cron to attach the good uid to sorbonne_tv nodes
 */
function up1_global_hotfix_author_pages_sorbonnetv() {
    $site = Site::load(126);

    if ($site) {
        $mail = $site->getEmail();
        $owner = user_load_by_mail($mail);
        if ($owner) {
            $owner_id = $owner->id();

            $ids = \Drupal::entityQuery('node')
                ->condition('type', 'page_sorbonne_tv')
                ->accessCheck(FALSE)
                ->execute();

            if (!empty($ids)) {

                $nodes = Node::loadMultiple($ids);
                foreach ($nodes as $node) {
                    if($node->getOwnerId() != $owner_id) {
                        $node->set('uid', $owner_id);
                        $node->save();
                    }
                }
            }
            else {
                \Drupal::logger('sorbonne_tv_HOTFIX:NODES')->notice('No node found.');
            }
        }
        else {
            \Drupal::logger('sorbonne_tv_HOTFIX:OWNER')->notice('Site\'s owner not found.');
        }
    }
    else {
        \Drupal::logger('sorbonne_tv_HOTFIX:SITE')->notice('Site Sorbonne TV not found.');
    }
}



