<?php

/**
 * @file
 * Contains up1_global.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function up1_global_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the up1_global module.
    case 'help.page.up1_global':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Defines global functions to be reused in other UP1 modules') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_alter().
 */
function up1_global_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == "node_offer_form") {
    $form['field_type']['#autocomplete_route_name'] = 'up1_global.referens';
    $form['field_type']['#autocomplete_route_parameters'] = [
      'bap' => 'bap',
    ];
  }
  if($form_id == "centres_up1_form"){
    $form['submit']['#value'] = html_entity_decode('&#xf002;');
    $form['submit']['#value']['#attributes']['class'][] = 'reset-btn search-btn';
  }
  if ($form['#id'] == "views-exposed-form-recherche-de-contenu-page-1"){
    $form["actions"]['submit']['#value'] = html_entity_decode('&#xf054;');
  }

}

/**
 * Implements hook_theme().
 */
function up1_global_theme($existing, $type, $theme, $path) {
  return [
   'date_range_formatter' => [
     'variables' => [],
     'template' => 'date-range-formatter',
   ],
    'up1_ent_search_block' => [
      'variables' => ['url' => NULL, 'theme_url' => NULL],
      'template' => 'up1-ent-search-block',
    ]
  ];
}
