title: Contacto
settings:
  confirmation_message: 'Se ha enviado su mensaje.'
handlers:
  email_confirmation:
    label: 'Courriel de confirmation'
  email_notification:
    label: 'Aviso por correo electrónico'
