label: المحتوى
description: 'إيجاد وإدارة المحتوى'
display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: انتقاء
          reset_button_label: 'إعادة الضبط'
          exposed_sorts_label: 'الترتيب حسب'
          sort_asc_label: تصاعدي
          sort_desc_label: تنازلي
      pager:
        options:
          tags:
            previous: '‹ Précédent'
            next: 'Suivant ›'
            first: '« Premier'
            last: 'Dernier »'
      fields:
        title:
          label: العنوان
        type:
          label: 'نوع المحتوى'
          separator: ', '
        name:
          label: المؤلف
        status:
          label: الحالة
          settings:
            format_custom_true: منشور
            format_custom_false: 'Non publié'
        changed:
          label: التحديث
        operations:
          label: عمليات
      filters:
        title:
          expose:
            label: العنوان
        type:
          expose:
            label: 'نوع المحتوى'
        status:
          expose:
            label: الحالة
          group_info:
            label: 'Statut de publication'
            group_items:
              1:
                title: منشور
              2:
                title: 'Non publié'
        langcode:
          expose:
            label: اللغة
      title: المحتوى
      empty:
        area_text_custom:
          content: 'لا يوجد محتوى.'
    display_title: الرئيسي
  page_1:
    display_options:
      menu:
        title: المحتوى
      tab_options:
        title: المحتوى
        description: 'Trouver et gérer le contenu'
    display_title: الصفحة
