display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: انتقاء
          reset_button_label: 'إعادة الضبط'
          exposed_sorts_label: 'الترتيب حسب'
          sort_asc_label: تصاعدي
          sort_desc_label: تنازلي
      pager:
        options:
          tags:
            previous: '‹ السابقة'
            next: 'التالية ›'
            first: '« الأولى'
            last: 'الأخيرة »'
      fields:
        node_bulk_form:
          action_title: إجراء
        title:
          label: العنوان
          separator: ', '
        type:
          separator: ', '
        name:
          label: المؤلف
          separator: ', '
        status:
          label: الحالة
          settings:
            format_custom_true: منشور
            format_custom_false: 'Non publié'
          separator: ', '
        publish_on:
          separator: ', '
        unpublish_on:
          separator: ', '
        operations:
          label: عمليات
      filters:
        title:
          expose:
            label: العنوان
        type:
          expose:
            label: 'نوع المحتوى'
        status:
          expose:
            label: الحالة
          group_info:
            label: 'Statut de publication'
            group_items:
              1:
                title: منشور
              2:
                title: 'Non publié'
        langcode:
          expose:
            label: اللغة
    display_title: الرئيسي
  overview:
    display_options:
      tab_options:
        title: المحتوى
  user_page:
    display_options:
      tab_options:
        title: المحتوى
      arguments:
        uid:
          exception:
            title: الكل
