<?php
/**
 * @file
 * Bootstrap sub-theme.
 *
 * Place your custom PHP code in this file.
 */

function PARIS12018_preprocess_page(&$variables) {
	$language = \Drupal::languageManager()->getCurrentLanguage()->getId();
    $variables['language'] = $language;
}

function PARIS12018_preprocess_links(&$variables) {
	$language = \Drupal::languageManager()->getCurrentLanguage()->getId();
    $variables['language'] = $language;
}