<?php

/**
 * @file
 * Contains up1_keywords.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function up1_keywords_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the up1_keywords module.
    case 'help.page.up1_keywords':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Mots clés saisonniers') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function up1_keywords_theme() {
  return [
    'up1_keywords' => [
      'template' => 'up1-keywords',
      'variables' => [
        'keywords' => [],
		'keywordslinks' => [],
		'menu'=> NULL,
        'search' => [],
        'url' => NULL],
		
    ],
  ];
}

function _up1_keywords_render_menu_navigation($menu_name,$theme_alter = ''){
    //Set system menu mobile
    $menu_tree = \Drupal::menuTree();
    // Build the typical default set of menu tree parameters.
    $parameters = $menu_tree->getCurrentRouteMenuTreeParameters($menu_name);
    // Load the tree based on this set of parameters.
    $tree = $menu_tree->load($menu_name, $parameters);
    // Transform the tree using the manipulators you want.
    $manipulators = array(
        // Only show links that are accessible for the current user.
        array('callable' => 'menu.default_tree_manipulators:checkAccess'),
        // Use the default sorting of menu links.
        array('callable' => 'menu.default_tree_manipulators:generateIndexAndSort'),
    );
    $tree = $menu_tree->transform($tree, $manipulators);
    // Finally, build a renderable array from the transformed tree.
    $menu = $menu_tree->build($tree);
    if(!empty($theme_alter)){
        $menu['#theme'] = $theme_alter;
    }
    return \Drupal::service('renderer')->render($menu);
}