<?php

/**
 * @file
 * Contains micro_cas_affiliation.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\user\UserInterface;
use \Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function micro_cas_affiliation_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the micro_cas_affiliation module.
    case 'help.page.micro_cas_affiliation':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Assigner un role et un sous site a un utilisateur') . '</p>';
      return $output;

    default:
  }
}

function micro_cas_affiliation_entity_base_field_info(EntityTypeInterface $entity_type) {
  $fields = [];

  if ($entity_type->id() === 'site') {
    $fields['bypass_site_users'] = BaseFieldDefinition::create('boolean')
      ->setLabel(t('Bypass site users check for this site.'))
      ->setDescription(t('Authorize users to login on this site even if they are not in the site users list.'))
      ->setDefaultValue(FALSE)
      ->setRevisionable(TRUE)
      ->setDisplayOptions('form', [
        'weight' => 100,
      ])
      ->setDisplayConfigurable('form', TRUE);
  }

  return $fields;
}

function micro_cas_affiliation_form_site_form_alter(&$form, FormStateInterface $form_state, $form_id) {
	
  if (isset($form['bypass_site_users'])) {
    $form['bypass_site_users']['#group'] = 'shield_info';
  }
}
