_core:
  default_config_hash: yXadRE77Va-G6dxhd2kPYapAvbnSvTF6hO4oXiOEynI
langcode: fr
uuid: cc432ebb-c98a-48be-8a1b-aa1035fc1131
name: 'Université Paris 1 Panthéon-Sorbonne'
mail: Liliana.Helmany@univ-paris1.fr
slogan: ''
page:
  403: ''
  404: /404
  front: /node/1
admin_compact_mode: false
weight_select_max: 100
default_langcode: fr
mail_notification: ''
