keywords_links:
  -
    uri: 'https://www--ppd.pantheonsorbonne.fr/universite/grands-evenements/destination-rentree-en-toute-serenite'
    title: 'tag 1'
  -
    uri: 'https://50ans--ppd.pantheonsorbonne.fr/'
    title: '50 ans'
  -
    uri: 'https://www--ppd.pantheonsorbonne.fr/inscription'
    title: Inscription
  -
    uri: 'https://www--ppd.pantheonsorbonne.fr/una-europa'
    title: 'Una Europa'
  -
    uri: 'https://www--ppd.pantheonsorbonne.fr/'
    title: 'tag 2'
  -
    uri: ''
    title: ''
link: null
