<?php

/**
 * @file up1_move_to_trash.module
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Form\FormStateInterface;
use Drupal\user\Entity\User;

/**
 * Implements hook_help().
 */
function up1_move_to_trash_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.up1_move_to_trash':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('') . '</p>';

      return $output;
    default:
  }
}

/**
 * Implements hook_entity_base_field_info().
 */
function up1_move_to_trash_entity_base_field_info(EntityTypeInterface $entity_type) {
  $fields = [];

  if ($entity_type->id() === 'node') {
    $fields['move_to_trash'] = BaseFieldDefinition::create('boolean')
      ->setLabel(t('Move to trash'))
      ->setDescription(t('If enabled, move this node to trash instead of definitive deletion'))
      ->setRevisionable(TRUE)
      ->setTranslatable(TRUE)
      ->setDefaultValue(TRUE)
      ->setDisplayOptions('form', array(
        'type' => 'boolean_checkbox',
        'settings' => array(
          'display_label' => TRUE,
        ),
        'weight' => 15,
      ));
    $fields['deleted'] = BaseFieldDefinition::create('changed')
      ->setLabel(t('Deleted on'))
      ->setDescription(t('The time that the node was deleted.'))
      ->setRevisionable(TRUE)
      ->setTranslatable(TRUE)
      ->setDisplayOptions('view', array(
        'label' => 'hidden',
        'type' => 'timestamp',
        'weight' => 0,
      ))
      ->setDisplayOptions('form', array(
        'type' => 'datetime_timestamp',
        'weight' => 10,
      ))
      ->setDisplayConfigurable('form', TRUE);
  }

  return $fields;
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function up1_move_to_trash_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['deletion'] = [
    '#type' => 'details',
    '#title' => t('Move to trash'),
    '#group' => 'advanced',
    '#attributes' => [
      'class' => ['node-form-options'],
    ],
    '#attached' => [
      'library' => ['node/drupal.node'],
    ],
    '#weight' => 102,
    '#optional' => TRUE,
  ];

  if (isset($form['move_to_trash'])) {
    $form['move_to_trash']['#group'] = 'deletion';
  }
  if (isset($form['deleted'])) {
    $form['move_to_trash']['#group'] = 'deletion';
    $form['deleted']['#disabled'] = TRUE;
  }

  $account = User::load(\Drupal::currentUser()->id());
  if (!$account->hasRole('administrator')) {
    $form['actions']['delete']['#access'] = FALSE;
  }
}
