_core:
  default_config_hash: Ws80dA0r_3vsw6I-EIauGqduZJCloQeye3IRJ2ypW6E
date_format_exif: null
granularity: 0
mediatypes:
  image: image
  mediatheque: mediatheque
  remote_video: remote_video
  video: video
  audio: '0'
  file: '0'
  mediatheque_audio: '0'
  sorbonne_tv_picto: '0'
nodetypes:
  event: event
  news: news
  page: page
  press: press
  second_level_pages: second_level_pages
  aap: '0'
  article: '0'
  email: '0'
  news2018: '0'
  offer: '0'
  page_personnelle: '0'
  page_sorbonne_tv: '0'
  publication: '0'
  viva: '0'
filetypes: {  }
update_metadata: true
vocabulary: '0'
write_empty_values: false
extraction_solution: php_extensions
exiftool_location: exiftool
