<?php

namespace Drupal\up1_archive\Form;

use Drupal\Core\Form\ConfigFormBase;
use Drupal\Core\Form\FormStateInterface;

/**
 * Class ArchiveSettings.
 *
 * @ingroup up1_archive
 */
class ArchiveSettings extends ConfigFormBase {
  /**
   * {@inheritdoc}
   */
  protected function getEditableConfigNames()
  {
    return [
      'up1_archive.settings',
    ];
  }

  /**
   * Returns a unique string identifying the form.
   *
   * @return string
   *   The unique string identifying the form.
   */
  public function getFormId()
  {
    return 'up1_archive_settings';
  }

  /**
   * @param array $form
   * @param FormStateInterface $form_state
   * @return void
   */
  public function validateForm(array &$form, FormStateInterface $form_state)
  {
    parent::validateForm($form, $form_state); // TODO: Change the autogenerated stub
  }

  /**
   * @param array $form
   * @param FormStateInterface $form_state
   * @return void
   */
  public function submitForm(array &$form, FormStateInterface $form_state)
  {
    parent::submitForm($form, $form_state);
    $this->config('up1_archive.settings')
      ->set('url_web', $form_state->getValue('url_web'))
      ->set('access_key', $form_state->getValue('access_key'))
      ->set('secret_key', $form_state->getValue('secret_key'))
      ->set('url_node', $form_state->getValue('url_node'))
      ->set('nid', $form_state->getValue('nid'))
      ->save();
  }

  /**
   * @param array $form
   * @param FormStateInterface $form_state
   * @return array
   */
  public function buildForm(array $form, FormStateInterface $form_state) {
    $config = $this->config('up1_archive.settings');
    $url_web = $config->get('url_web');
    $access_key =  $config->get('access_key');
    $secret_key = $config->get('secret_key');
    $url_node = $config->get('url_node');
    $nid = $config->get('nid');

    $form['archive'] = [
      '#type' => 'details',
      '#title' => t('Web archive parameters'),
      '#weight' => 50,
      '#open' => TRUE,
    ];
    $form['archive']['url_web'] = [
      '#type' => 'textfield',
      '#title' => $this->t('URL du site d\'archives web.'),
      '#description' => $this->t('Par défaut : "https://web.archive.org/save"'),
      '#maxlength' => 64,
      '#size' => 64,
      '#default_value' => isset($url_web) ? $url_web : "https://web.archive.org/save",
      '#required' => TRUE
    ];
    $form['archive']['access_key'] = [
      '#type' => 'textfield',
      '#title' => $this->t('Access Key.'),
      '#description' => $this->t('archive.org S3 API Keys.'),
      '#maxlength' => 128,
      '#size' => 64,
      '#default_value' => isset($access_key) ? $access_key : "",
      '#required' => TRUE
    ];
    $form['archive']['secret_key'] = [
      '#type' => 'textfield',
      '#title' => $this->t('Secret Key.'),
      '#description' => $this->t('archive.org S3 API Keys.'),
      '#maxlength' => 64,
      '#size' => 64,
      '#default_value' => isset($secret_key) ? $secret_key : "",
      '#required' => TRUE
    ];
    $form['node'] = [
      '#type' => 'details',
      '#title' => t('Page(s) to archive'),
      '#weight' => 50,
      '#open' => TRUE,
    ];
    $form['node']['url_node'] = [
      '#type' => 'textfield',
      '#title' => $this->t('URL du node à archiver.'),
      '#description' => $this->t('Par exemple : "https://pantheonsorbonne.fr/universite/publications-reglementaires"'),
      '#maxlength' => 256,
      '#size' => 64,
      '#default_value' =>  isset($url_node) ? $url_node : "",
      '#required' => TRUE
    ];
    $form['node']['nid'] = [
      '#type' => 'textfield',
      '#title' => $this->t('Id du noeud à archiver.'),
      '#description' => $this->t('Par exemple : 31866'),
      '#maxlength' => 10,
      '#size' => 64,
      '#default_value' => isset($nid) ? $nid : "",
      '#required' => TRUE
    ];

    return parent::buildForm($form, $form_state);
  }
}
