label: Content
description: 'Trouver et gérer le contenu.'
display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
      pager:
        options:
          tags:
            previous: '‹ Précédent'
            next: 'Suivant ›'
            first: '« First'
            last: 'Last »'
      fields:
        title:
          label: Title
        type:
          label: 'Type de contenu'
        name:
          label: Author
        status:
          label: État
          settings:
            format_custom_true: Published
            format_custom_false: 'Non publié'
        changed:
          label: 'Mis à jour'
        operations:
          label: Actions
      filters:
        title:
          expose:
            label: Title
        type:
          expose:
            label: 'Type de contenu'
        status:
          expose:
            label: État
          group_info:
            label: 'Statut de publication'
            group_items:
              1:
                title: Published
              2:
                title: 'Non publié'
        langcode:
          expose:
            label: Langue
      title: Content
      empty:
        area_text_custom:
          content: 'Aucun contenu disponible.'
    display_title: Master
  page_1:
    display_options:
      menu:
        title: Content
      tab_options:
        title: Content
        description: 'Trouver et gérer le contenu'
