label: Surveillance
description: 'Entrées récentes du journal'
display:
  default:
    display_title: Default
    display_options:
      title: 'Entrées récentes du journal'
      fields:
        nothing:
          admin_label: Icône
        severity:
          label: Importance
        name:
          label: User
        link:
          label: Operations
      pager:
        options:
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
      empty:
        area:
          admin_label: 'Aucune entrée du journal n''est disponible.'
          content: 'Aucune entrée du journal n''est disponible.'
      filters:
        severity:
          expose:
            label: Importance
  page:
    display_title: Page
