<?php

/**
 * @file
 * Contains up1_events.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function up1_events_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the up1_events module.
    case 'help.page.up1_events':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module lié au content type event') . '</p>';
      return $output;

    default:
  }
}
