<?php

/**
 * @file
 * Contains up1_pages_perso.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function up1_pages_perso_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the up1_pages_perso module.
    case 'help.page.up1_pages_perso':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module permettant la construction et la presentation des pages persos des enseignants-chercheurs &amp; doctorants à partir des différents web services') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function up1_pages_perso_theme() {
  $theme = [];
  $theme['page_perso'] = [
    'render element' => 'elements',
    'file' => 'page_perso.page.inc',
    'template' => 'page_perso',
  ];
  $theme['page_perso_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'page_perso.page.inc',
  ];
  return $theme;
}

/**
* Implements hook_theme_suggestions_HOOK().
*/
function up1_pages_perso_theme_suggestions_page_perso(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#page_perso'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'page_perso__' . $sanitized_view_mode;
  $suggestions[] = 'page_perso__' . $entity->bundle();
  $suggestions[] = 'page_perso__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'page_perso__' . $entity->id();
  $suggestions[] = 'page_perso__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
