_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
langcode: fr
module:
  micro_menu: -1
  admin_toolbar: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  adminimal_admin_toolbar: 0
  amp: 0
  amp_toolbar: 0
  anchor_link: 0
  automated_cron: 0
  better_exposed_filters: 0
  block: 0
  block_content: 0
  body_node_id_class: 0
  bootstrap_paragraphs: 0
  breakpoint: 0
  captcha: 0
  cas: 0
  cas_attributes: 0
  chosen: 0
  chosen_field: 0
  chosen_lib: 0
  ckeditor: 0
  ckeditor_a11ychecker: 0
  ckeditor_abbreviation: 0
  ckeditor_balloonpanel: 0
  cmis: 0
  cmis_extensions: 0
  comment: 0
  conditional_fields: 0
  config: 0
  config_filter: 0
  config_split: 0
  config_translation: 0
  contact: 0
  content_moderation: 0
  content_moderation_notifications: 0
  contextual: 0
  crop: 0
  csv_serialization: 0
  ctools: 0
  custom_500_error: 0
  date_popup: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  devel: 0
  dropzonejs: 0
  dropzonejs_eb_widget: 0
  dynamic_page_cache: 0
  easy_breadcrumb: 0
  editor: 0
  editor_file: 0
  elasticsearch_connector: 0
  elasticsearch_connector_autocomp: 0
  embed: 0
  entity_activity: 0
  entity_activity_mail: 0
  entity_browser: 0
  entity_browser_entity_form: 0
  entity_embed: 0
  entity_reference_revisions: 0
  facets: 0
  facets_custom_label: 0
  fakeobjects: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  flag: 0
  focal_point: 0
  fontawesome: 0
  force_users_logout: 0
  geofield: 0
  geolocation: 0
  geolocation_leaflet: 0
  gutenberg: 0
  help: 0
  history: 0
  ics_field: 0
  image: 0
  image_field_360: 0
  inline_entity_form: 0
  jquery_minicolors: 0
  jquery_ui: 0
  jquery_ui_accordion: 0
  jquery_ui_autocomplete: 0
  jquery_ui_datepicker: 0
  jquery_ui_menu: 0
  jquery_ui_slider: 0
  jquery_ui_touch_punch: 0
  language: 0
  layout_discovery: 0
  link: 0
  link_attributes: 0
  linkit: 0
  locale: 0
  mailsystem: 0
  matomo: 0
  matomo_reports: 0
  media: 0
  media_directories: 0
  media_directories_editor: 0
  media_directories_ui: 0
  media_entity_browser: 0
  media_library: 0
  media_oembed_control: 0
  menu_breadcrumb: 0
  menu_per_role: 0
  menu_ui: 0
  metatag: 0
  metatag_extended_perms: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  micro_cas_affiliation: 0
  micro_dashboard: 0
  micro_footer: 0
  micro_homepage: 0
  micro_media: 0
  micro_menu_clean: 0
  micro_multilingue: 0
  micro_node: 0
  micro_node_redirect: 0
  micro_path: 0
  micro_reports: 0
  micro_scheduler: 0
  micro_site: 0
  micro_site_pickup: 0
  micro_social_media: 0
  micro_taxonomy: 0
  micro_theme: 0
  micro_theme_library: 0
  micro_title_size: 0
  micro_user: 0
  mimemail: 0
  module_filter: 0
  mysql: 0
  nbsp: 0
  node: 0
  options: 0
  page_cache: 0
  page_manager: 0
  page_manager_ui: 0
  page_specific_class: 0
  panels: 0
  paragraphs_features: 0
  path: 0
  path_alias: 0
  permissions_by_term: 0
  quick_node_clone: 0
  recaptcha: 0
  redirect: 0
  redirect_domain: 0
  responsive_image: 0
  rest: 0
  restrict_route_by_ip: 0
  robotstxt: 0
  rules: 0
  rules_token: 0
  scheduler: 0
  scheduler_content_moderation_integration: 0
  schema_metatag: 0
  search404: 0
  search_api: 0
  search_api_autocomplete: 0
  search_api_db: 0
  search_api_db_defaults: 0
  serialization: 0
  shortcut: 0
  siteimprove: 0
  smtp: 0
  social_simple: 0
  system: 0
  taxonomy: 0
  text: 0
  text_or_entity: 0
  token: 0
  token_filter: 0
  toolbar: 0
  total_control: 0
  tour: 0
  typed_data: 0
  up1_data_import: 0
  up1_global: 0
  up1_keywords: 0
  up1_mediatheque_source: 0
  up1_pages_personnelles: 0
  up1_theses: 0
  update: 0
  upgrade_rector: 0
  user: 0
  views_bootstrap: 0
  views_bulk_edit: 0
  views_data_export: 0
  views_infinite_scroll: 0
  views_slideshow: 0
  views_slideshow_cycle: 0
  views_templates: 0
  views_timelinejs: 0
  views_ui: 0
  viewsreference: 0
  webform: 0
  webform_attachment: 0
  webform_ui: 0
  workflow_notifications: 0
  workflows: 0
  extlink: 1
  menu_link_content: 1
  pathauto: 1
  xmlsitemap: 1
  content_translation: 10
  externalauth: 10
  views: 10
  paragraphs: 11
  paragraphs_sets: 12
  paragraphs_ee: 15
  standard: 1000
theme:
  stable: 0
  seven: 0
  adminimal_theme: 0
  bootstrap: 0
  p1ps2019: 0
  amptheme: 0
  ampsubtheme_example: 0
  claro: 0
profile: standard
