privacy:
  disablecookies: false
  donottrack: true
langcode: fr
site_id: '40'
url_http: 'http://stats.univ-paris1.fr/'
url_https: 'https://stats.univ-paris1.fr/'
codesnippet:
  before: ''
  after: ''
custom:
  variable:
    1:
      name: ''
      value: ''
      scope: visit
      slot: 1
    2:
      name: ''
      value: ''
      scope: visit
      slot: 2
    3:
      name: ''
      value: ''
      scope: visit
      slot: 3
    4:
      name: ''
      value: ''
      scope: visit
      slot: 4
    5:
      name: ''
      value: ''
      scope: visit
      slot: 5
domain_mode: 0
track:
  files: true
  files_extensions: '7z|aac|arc|arj|asf|asx|avi|bin|csv|doc(x|m)?|dot(x|m)?|exe|flv|gif|gz|gzip|hqx|jar|jpe?g|js|mp(2|3|4|e?g)|mov(ie)?|msi|msp|pdf|phps|png|ppt(x|m)?|pot(x|m)?|pps(x|m)?|ppam|sld(x|m)?|thmx|qtm?|ra(m|r)?|sea|sit|tar|tgz|torrent|txt|wav|wma|wmv|wpd|xls(x|m|b)?|xlt(x|m)|xlam|xml|z|zip'
  colorbox: false
  userid: false
  mailto: true
  messages: {  }
  site_search: false
page_title_hierarchy: false
page_title_hierarchy_exclude_home: true
cache: false
visibility:
  request_path_mode: null
  request_path_pages: ''
  user_account_mode: 1
  user_role_mode: null
  user_role_roles: {  }
translation_set: false
