<?php

/**
 * @file
 * Contains micro_menu_clean.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function micro_menu_clean_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the micro_menu_clean module.
    case 'help.page.micro_menu_clean':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('affichage des menus de mini site') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_menu_links_discovered_alter().
 */
function micro_menu_clean_menu_links_discovered_alter(&$links) {


  foreach ($links as $key => $link){
    if (strpos($key, 'edit_form.site-') !== false){
      $links[$key]['parent'] = 'micro_menu_clean.mini_sites';
    }
  }

}

/**
 * Implements hook_form_alter().
 */
function micro_menu_clean_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'node_type_edit_form' || $form_id == 'node_type_add_form'){
    $menu_options = $form['menu']['menu_options']['#options'];
    foreach ($menu_options as $key => $option){
      if (strpos($key, 'site-')!== FALSE){
        unset($form['menu']['menu_options']['#options'][$key]);
      }
    }
  }
}