label: 'Contenu programmé'
display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Filtrer
          reset_button_label: Zurücksetzen
          exposed_sorts_label: 'Sortieren nach'
          sort_asc_label: Aufsteigend
          sort_desc_label: Absteigend
      pager:
        options:
          tags:
            previous: '‹ vorherige Seite'
            next: 'nächste Seite ›'
            first: '« erste Seite'
            last: 'letzte Seite »'
      fields:
        node_bulk_form:
          action_title: Aktion
        title:
          label: Titel
          separator: ', '
        type:
          label: 'Type de contenu'
          separator: ', '
        name:
          label: Autor
          separator: ', '
        status:
          label: État
          settings:
            format_custom_true: Veröffentlicht
            format_custom_false: 'Nicht veröffentlicht'
          separator: ', '
        publish_on:
          label: 'À publier le'
          separator: ', '
        unpublish_on:
          label: 'À dépublier le'
          separator: ', '
        operations:
          label: Aktionen
      filters:
        title:
          expose:
            label: Titel
        type:
          expose:
            label: Inhaltstyp
        status:
          expose:
            label: État
          group_info:
            label: 'Status veröffentlicht'
            group_items:
              1:
                title: Veröffentlicht
              2:
                title: 'Nicht veröffentlicht'
        langcode:
          expose:
            label: Sprache
      title: 'Contenu programmé'
    display_title: Master
  overview:
    display_options:
      menu:
        title: 'Contenu programmé'
      tab_options:
        title: Inhalt
    display_title: 'Content Overview'
  user_page:
    display_options:
      menu:
        title: Zeitgesteuert
      tab_options:
        title: Inhalt
      display_description: 'Onglet "contenu planifié" sur le profil utilisateur, montrant que l''utilisateur a programmé un contenu'
      arguments:
        uid:
          exception:
            title: Alle
    display_title: Benutzer
