# Schema for the configuration files of up1_move_to_trash module.
action.configuration.move_to_trash:
  type: action_configuration_default
  label: 'Move content to trash'

action.configuration.restore_content:
  type: action_configuration_default
  label: 'Restore content from trash'
