description: 'Tous les contenus, triés par lettre.'
display:
  default:
    display_options:
      fields:
        changed:
          label: 'Dernière mise à jour'
  attachment_1:
    display_title: 'Fichier attaché'
