display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Filter
      pager:
        options:
          tags:
            previous: '‹ previous'
            next: 'next ›'
            first: '« first'
            last: 'last »'
      fields:
        status:
          label: Status
          settings:
            format_custom_false: Unpublished
        operations:
          label: Operations
      filters:
        type:
          expose:
            label: 'Content type'
        status:
          expose:
            label: Status
          group_info:
            label: 'Published status'
            group_items:
              2:
                title: Unpublished
        langcode:
          expose:
            label: Language
  overview:
    display_options:
      tab_options:
        title: Content
  user_page:
    display_options:
      tab_options:
        title: Content
      arguments:
        uid:
          exception:
            title: All
